### ISSUE TITLE
Background cover image shows above navbar when user overscrolls.

### ISSUE THREAD

**Issue by dmortensen** [dmortensen/dangfinallee#2]
This can be prevented by adding the following to `.main`:

``` css
.main {
  position: relative;
  z-index: 1;
  overflow: hidden;
}
```
